### ISSUE TITLE
Crashses after mob render

### ISSUE THREAD

**Issue by xgammersx** [bspkrs-mods/bspkrsCore#16]
[16:31:49] [Client thread/INFO] [bspkrsCore]: Enabling Main Menu Mob render ticker
[OptiFine] **\* Reloading custom textures ***
[OptiFine] Loading custom colors: textures/colormap/grass.png
[OptiFine] Loading custom colors: textures/colormap/foliage.png
[16:31:50] [Client thread/INFO] [STDOUT]: [enviromine.handlers.EM_ServerScheduledTickHandler:RenderTickEvent:57]: First Load...
[16:31:50] [Client thread/INFO] [enviromine]: Config load successful.
[16:31:50] [Client thread/INFO] [FML]: InvTweaks: net.minecraft.inventory.ContainerWorkbench
[16:32:41] [Client thread/INFO] [bspkrsCore]: Enabling Main Menu Mob render ticker
[16:32:49] [Client thread/INFO] [FML]: InvTweaks: net.minecraft.client.gui.GuiTextField
[16:32:49] [Client thread/INFO] [FML]: InvTweaks: successfully transformed setFocused/func_146195_b
[16:33:00] [Client thread/INFO] [bspkrsCore]: Enabling Main Menu Mob render ticker
[16:33:33] [Client thread/FATAL]: Reported exception thrown!
net.minecraft.util.ReportedException: Starting integrated server
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1643) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962) ~[bao.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887) [bao.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_72]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.11.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.11.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
    at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_72]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:165) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.ExceptionInInitializerError
    at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:146) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:43) ~[bsx.class:?]
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2080) ~[bao.class:?]
    at adubbz.lockdown.gui.GuiCreateFixedWorld.func_146284_a(GuiCreateFixedWorld.java:80) ~[GuiCreateFixedWorld.class:?]
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225) ~[bdw.class:?]
    at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:377) ~[bdb.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296) ~[bdw.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) ~[bdw.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629) ~[bao.class:?]
    ... 17 more
Caused by: java.lang.IllegalStateException: failed to create a child event loop
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:61) ~[MultithreadEventExecutorGroup.class:?]
    at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49) ~[MultithreadEventLoopGroup.class:?]
    at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61) ~[NioEventLoopGroup.class:?]
    at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52) ~[NioEventLoopGroup.class:?]
    at net.minecraft.network.NetworkSystem.<clinit>(NetworkSystem.java:47) ~[nc.class:?]
    at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:146) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:43) ~[bsx.class:?]
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2080) ~[bao.class:?]
    at adubbz.lockdown.gui.GuiCreateFixedWorld.func_146284_a(GuiCreateFixedWorld.java:80) ~[GuiCreateFixedWorld.class:?]
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225) ~[bdw.class:?]
    at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:377) ~[bdb.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296) ~[bdw.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) ~[bdw.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629) ~[bao.class:?]
    ... 17 more
Caused by: io.netty.channel.ChannelException: failed to open a new selector
    at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:128) ~[NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:120) ~[NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:87) ~[NioEventLoopGroup.class:?]
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:57) ~[MultithreadEventExecutorGroup.class:?]
    at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49) ~[MultithreadEventLoopGroup.class:?]
    at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61) ~[NioEventLoopGroup.class:?]
    at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52) ~[NioEventLoopGroup.class:?]
    at net.minecraft.network.NetworkSystem.<clinit>(NetworkSystem.java:47) ~[nc.class:?]
    at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:146) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:43) ~[bsx.class:?]
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2080) ~[bao.class:?]
    at adubbz.lockdown.gui.GuiCreateFixedWorld.func_146284_a(GuiCreateFixedWorld.java:80) ~[GuiCreateFixedWorld.class:?]
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225) ~[bdw.class:?]
    at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:377) ~[bdb.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296) ~[bdw.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) ~[bdw.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629) ~[bao.class:?]
    ... 17 more
Caused by: java.io.IOException: Unable to establish loopback connection
    at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source) ~[?:1.7.0_72]
    at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source) ~[?:1.7.0_72]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_72]
    at sun.nio.ch.PipeImpl.<init>(Unknown Source) ~[?:1.7.0_72]
    at sun.nio.ch.SelectorProviderImpl.openPipe(Unknown Source) ~[?:1.7.0_72]
    at java.nio.channels.Pipe.open(Unknown Source) ~[?:1.7.0_72]
    at sun.nio.ch.WindowsSelectorImpl.<init>(Unknown Source) ~[?:1.7.0_72]
    at sun.nio.ch.WindowsSelectorProvider.openSelector(Unknown Source) ~[?:1.7.0_72]
    at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:126) ~[NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:120) ~[NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:87) ~[NioEventLoopGroup.class:?]
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:57) ~[MultithreadEventExecutorGroup.class:?]
    at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49) ~[MultithreadEventLoopGroup.class:?]
    at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61) ~[NioEventLoopGroup.class:?]
    at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52) ~[NioEventLoopGroup.class:?]
    at net.minecraft.network.NetworkSystem.<clinit>(NetworkSystem.java:47) ~[nc.class:?]
    at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:146) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:43) ~[bsx.class:?]
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2080) ~[bao.class:?]
    at adubbz.lockdown.gui.GuiCreateFixedWorld.func_146284_a(GuiCreateFixedWorld.java:80) ~[GuiCreateFixedWorld.class:?]
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225) ~[bdw.class:?]
    at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:377) ~[bdb.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296) ~[bdw.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) ~[bdw.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629) ~[bao.class:?]
    ... 17 more
Caused by: java.net.ConnectException: Connection timed out: connect
    at sun.nio.ch.Net.connect0(Native Method) ~[?:1.7.0_72]
    at sun.nio.ch.Net.connect(Unknown Source) ~[?:1.7.0_72]
    at sun.nio.ch.Net.connect(Unknown Source) ~[?:1.7.0_72]
    at sun.nio.ch.SocketChannelImpl.connect(Unknown Source) ~[?:1.7.0_72]
    at java.nio.channels.SocketChannel.open(Unknown Source) ~[?:1.7.0_72]
    at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source) ~[?:1.7.0_72]
    at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source) ~[?:1.7.0_72]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_72]
    at sun.nio.ch.PipeImpl.<init>(Unknown Source) ~[?:1.7.0_72]
    at sun.nio.ch.SelectorProviderImpl.openPipe(Unknown Source) ~[?:1.7.0_72]
    at java.nio.channels.Pipe.open(Unknown Source) ~[?:1.7.0_72]
    at sun.nio.ch.WindowsSelectorImpl.<init>(Unknown Source) ~[?:1.7.0_72]
    at sun.nio.ch.WindowsSelectorProvider.openSelector(Unknown Source) ~[?:1.7.0_72]
    at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:126) ~[NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:120) ~[NioEventLoop.class:?]
    at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:87) ~[NioEventLoopGroup.class:?]
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:57) ~[MultithreadEventExecutorGroup.class:?]
    at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49) ~[MultithreadEventLoopGroup.class:?]
    at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61) ~[NioEventLoopGroup.class:?]
    at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52) ~[NioEventLoopGroup.class:?]
    at net.minecraft.network.NetworkSystem.<clinit>(NetworkSystem.java:47) ~[nc.class:?]
    at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:146) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:43) ~[bsx.class:?]
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2080) ~[bao.class:?]
    at adubbz.lockdown.gui.GuiCreateFixedWorld.func_146284_a(GuiCreateFixedWorld.java:80) ~[GuiCreateFixedWorld.class:?]
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225) ~[bdw.class:?]
    at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:377) ~[bdb.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296) ~[bdw.class:?]
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268) ~[bdw.class:?]
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629) ~[bao.class:?]
    ... 17 more
[16:33:34] [Client thread/INFO] [STDOUT]: [net.minecraft.client.Minecraft:func_71377_b:349]: ---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 12/27/14 4:33 PM
Description: Starting integrated server

java.lang.ExceptionInInitializerError
    at net.minecraft.server.MinecraftServer.<init>(MinecraftServer.java:146)
    at net.minecraft.server.integrated.IntegratedServer.<init>(IntegratedServer.java:43)
    at net.minecraft.client.Minecraft.func_71371_a(Minecraft.java:2080)
    at adubbz.lockdown.gui.GuiCreateFixedWorld.func_146284_a(GuiCreateFixedWorld.java:80)
    at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:225)
    at net.minecraft.client.gui.GuiCreateWorld.func_73864_a(GuiCreateWorld.java:377)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:296)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1629)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:962)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
    at org.multimc.EntryPoint.listen(EntryPoint.java:165)
    at org.multimc.EntryPoint.main(EntryPoint.java:54)
Caused by: java.lang.IllegalStateException: failed to create a child event loop
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:61)
    at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:49)
    at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:61)
    at io.netty.channel.nio.NioEventLoopGroup.<init>(NioEventLoopGroup.java:52)
    at net.minecraft.network.NetworkSystem.<clinit>(NetworkSystem.java:47)
    ... 26 more
Caused by: io.netty.channel.ChannelException: failed to open a new selector
    at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:128)
    at io.netty.channel.nio.NioEventLoop.<init>(NioEventLoop.java:120)
    at io.netty.channel.nio.NioEventLoopGroup.newChild(NioEventLoopGroup.java:87)
    at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:57)
    ... 30 more
Caused by: java.io.IOException: Unable to establish loopback connection
    at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
    at sun.nio.ch.PipeImpl$Initializer.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.nio.ch.PipeImpl.<init>(Unknown Source)
    at sun.nio.ch.SelectorProviderImpl.openPipe(Unknown Source)
    at java.nio.channels.Pipe.open(Unknown Source)
    at sun.nio.ch.WindowsSelectorImpl.<init>(Unknown Source)
    at sun.nio.ch.WindowsSelectorProvider.openSelector(Unknown Source)
    at io.netty.channel.nio.NioEventLoop.openSelector(NioEventLoop.java:126)
    ... 33 more
Caused by: java.net.ConnectException: Connection timed out: connect
    at sun.nio.ch.Net.connect0(Native Method)
    at sun.nio.ch.Net.connect(Unknown Source)
    at sun.nio.ch.Net.connect(Unknown Source)
    at sun.nio.ch.SocketChannelImpl.connect(Unknown Source)
    at java.nio.channels.SocketChannel.open(Unknown Source)
    ... 42 more

**Comment by bspkrs** [comment]
Set showMainMenuMobs=false in bspkrsCore.cfg and see if the issue still occurs.

**Comment by TurkishAhmet4545** [comment]
Thanks for answer.Your message helped me too.😊

**Comment by MichaelHillcox** [comment]
Last I checked it's been removed.
